### ISSUE TITLE
Menú “Opciones” dentro de Playlist #40

### ISSUE THREAD

**Issue by natanverdes** [tyrell-x/apollofy-client#1]
En la vista de playlist, accediendo al botón
“Opciones”, podrá editar los datos de la playlist (si es propietario), ver más información del creador, compartirla y eliminarla (si es propietario).

**Comment by Leyber91** [comment]
> En la vista de playlist, accediendo al botón
> “Opciones”, podrá editar los datos de la playlist (si es propietario), ver más información del creador, compartirla y eliminarla (si es propietario).

**This issue must be divided in separate tasks**

1. Generate the Options buttons inside the playlist view
2. Make the Edit Playlist modal
3. See more info pop up
4. Share playlist
5. Eliminate playlist if owner
